CREATE OR REPLACE VIEW VIEW_AMOSTRA_TEMPORAL_SUICIDIO AS
SELECT 
	SUICIDIO_BRA.year,
	SUICIDIO_BRA.sex,
	SUICIDIO_BRA.age,
	SUICIDIO_BRA.suicides_no
FROM VIEW_SUICIDIO SUICIDIO_BRA ORDER BY SUICIDIO_BRA.year ,SUICIDIO_BRA.sex, SUICIDIO_BRA.age;