CREATE TABLE HEART(
	HEART_ID BIGSERIAL NOT NULL,
	AGE BIGINT,
	SEX BIGINT,
	CHEST_PAIN_TYPE BIGINT,	
	TRESTBPS BIGINT,
	CHOL BIGINT,
	FBS BIGINT,
	RESTECG BIGINT,
	THALACH BIGINT,
	EXANG BIGINT,
	OLDPEAK DECIMAL(2,1),
	SLOPE BIGINT,
	CA BIGINT,
	THAL BIGINT,
	TARGET BIGINT,
	CONSTRAINT PK_HEART PRIMARY KEY(HEART_ID)
);